### ISSUE TITLE
Add `join` path functionality as part of the `FileSystemAdapter`

### ISSUE THREAD

**Issue by renehernandez** [obsidianmd/obsidian-api#12]
New `join` function. Ideally, this would be similar to [path.join](https://nodejs.org/api/path.html#path_path_join_paths) and would take care of using the correct separator in each platform. This would remove the need to write code like this: https://github.com/jamiebrynes7/obsidian-todoist-plugin/blob/cf4f1e0e9d452e24b642168610d0d20b218514ee/src/utils.ts#L54

**Comment by lishid** [comment]
If you're operating within Obsidian's Vault and Adapter API, then you should use `normalizePath` to normalize your paths, which will convert them into Obsidian's preferred format (always prefer `/`, remove duplicate `//`, strip first and last `/`).
https://github.com/obsidianmd/obsidian-api/blob/bbd5525cba2e0aefc27c87b378805c155ae8d5b1/obsidian.d.ts#L1863

If you're operating beyond the adapter API, then you are on your own, and should use NodeJS's API (because you'll have to use `require('fs')` anyway).
