### ISSUE TITLE
Bug: wrong view type when opening file twice

### ISSUE THREAD

**Issue by FlorianWoelki** [obsidianmd/obsidian-api#133]
I don't know if this is intended, but I would like to get the file whenever the user opens it (even when they click on it again without opening it in a new tab). I am using the `active-leaf-change` event. For the first opening of the file, the `leaf.view.getViewType()` is correct and the parameter `leaf` is a valid file. However, when I click on the same file again the `leaf.view.getViewType()` changes to `file-explorer` where the file itself is `undefined`.

I just wanted to ask if this is intended. If yes, how can I fix the issue, so that I always see the correct file, no matter how many times the user clicks on the file?

**Steps to reproduce:**
- Open a file with a simple left click (view type is `markdown`)
- Left click and open the file again (view type is `file-explorer`)

**Comment by lishid** [comment]
This is intended - if you click on the file explorer twice then it focuses the file explorer instead of the note leaf. In your case you are looking at the active leaf which is now a different leaf than the note.

Also `active-leaf-change` means the focused active leaf has changed, not that a file has been opened. If you have two tabs then switching between them will cause active leaf change events. Focusing on sidebar accessory panes will also cause that to trigger.
