### ISSUE TITLE
Obsidian Sync issue with icon-folder

### ISSUE THREAD

**Issue by FlorianWoelki** [obsidianmd/obsidian-api#134]
I would like to ask, what the right way is to store zip files or any other possible large files so that Obsidian sync successfully syncs the files. We are currently experiencing some issues with Sync and the [icon folder plugin](https://github.com/FlorianWoelki/obsidian-iconize).
You've already created one issue [here](https://github.com/FlorianWoelki/obsidian-iconize/issues/52). But that didn't really solve the issue for some users. So I've tried to add a new syncing mechanism that just adds the zip files which includes the icons. But that didn't really work either (see this [issue](https://github.com/FlorianWoelki/obsidian-iconize/issues/224#issuecomment-1722581936)).
So, I would like to ask, what's the right approach I need to follow for users not complaining anymore about syncing failures of this plugin?

**Comment by lishid** [comment]
If you're using a single file then you can put it in your plugin folder to have it synced with your plugin - other folders inside `.obsidian` is simply ignored which is why `.obsidian/icons/` is never synced.

The support reply seems to link to the previous discussions we've had:
> We've tried reaching out to them to make the .obsidian/icons/ the default behavior, but to no avail. https://github.com/FlorianWoelki/obsidian-iconize/issues/52

It seems like the plugin still defaults to unpacked icons in the plugin folder, which interferes with Sync functionality. I **highly** suggest defaulting the icon locations to NOT your plugin folder as it will get synced when the user chooses to sync their plugins, unless you pack them into a single file.

**Comment by FlorianWoelki** [comment]
> If you're using a single file then you can put it in your plugin folder to have it synced with your plugin - other folders inside `.obsidian` is simply ignored which is why `.obsidian/icons/` is never synced.
> 
> The support reply seems to link to the previous discussions we've had:
> 
> > We've tried reaching out to them to make the .obsidian/icons/ the default behavior, but to no avail. [FlorianWoelki/obsidian-iconize#52](https://github.com/FlorianWoelki/obsidian-iconize/issues/52)
> 
> It seems like the plugin still defaults to unpacked icons in the plugin folder, which interferes with Sync functionality. I **highly** suggest defaulting the icon locations to NOT your plugin folder as it will get synced when the user chooses to sync their plugins, unless you pack them into a single file.

Alright, thank you for the suggestion! I'll update the plugin so that the path defaults to `.obsidian/icons/`.

Thank you!

**Comment by lishid** [comment]
Because this plugin creates thousands of icon files which clogs up the syncing process. Moving it there precisely prevents these icons from being synced.
