### ISSUE TITLE
Bug: `app.setting` is not included in Type Definitions 

### ISSUE THREAD

**Issue by Cutaiar** [obsidianmd/obsidian-api#140]
`app.setting` is not included in the latest Type Definitions available on [npm](https://www.npmjs.com/package/obsidian) despite [widespread use](https://github.com/search?q=this.app.setting.&type=code) and [awareness](https://discord.com/channels/686053708261228577/840286264964022302/1070592103203221526).

**Comment by joethei** [comment]
Private APIs are not documented because they are private.
There are loads of methods and fields that exists at runtime but aren't in the API because we have not committed to supporting them through the API.

If you decide to use a private API you can do so by adding it in your own local .d.ts file in your plugin repo.

**Comment by Cutaiar** [comment]
Understood, thanks for the information. Just voicing an opinion here that an eventual public API opening settings would be useful to many plugins 🙂. 

For those that land here in the future, consider using / contributing to these unofficial but thorough [types](https://github.com/Fevol/obsidian-typings).
