### ISSUE TITLE
Bug: MarkdownRenderer.render does not add rendered links to metadataCache

### ISSUE THREAD

**Issue by mayurankv** [obsidianmd/obsidian-api#144]
I'm not 100% sure if this is a bug or intended behaviour but wanted to be sure!

**Steps to reproduce:**
- Calling `MarkdownRenderer.render(plugin.app, "[[file]]", linkEl, sourcePath, plugin)` does not add the rendered file to the `metadataCache` of the file specified by sourcePath.

**Comment by lishid** [comment]
MetadataCache is used to cache the parsing of the original file in the vault on disk. MarkdownRenderer.render is used to render some markdown string into a DOM element - the fact that it asks for a sourcePath is so that relative links in the markdown can be resolved properly from the correct perspective.

They are not related to one another.

**Comment by lishid** [comment]
There isn't a direct way - you need to edit the file itself to include the links.
