### ISSUE TITLE
Bug: Treating Longtime Users and Plugin Developers with Friendliness

### ISSUE THREAD

**Issue by fireflysss** [obsidianmd/obsidian-api#151]
Thank you for developing the Obsidian software platform. It's an excellent note-taking tool that is user-friendly and offers a wide range of features. Many users are increasingly adopting it, and there is a vibrant community of passionate plugin developers enhancing the software's capabilities.
However, in recent updates, there have been issues with loading local files using iframes, and the support for the "app://local" link has been removed, preventing the loading of external videos. This change was made for security reasons, but it has rendered some previously handy plugins unusable. Some plugin developers are also struggling to find solutions, causing hesitation among users to update to the latest version of Obsidian.
As a widely popular software, it's crucial to cater to the preferences of a diverse user base and provide a stable environment. The inability to open notes created with plugins can be disheartening. Additionally, it's essential to consider the efforts of enthusiastic plugin developers, ensuring that updates take into account the compatibility of widely used plugins.
If the changes are driven by security concerns, perhaps providing an option for users to choose whether to enable certain functionalities related to security, such as iframe loading of local files, could be considered. This way, users who rely on third-party plugins can have the option to enable features even if they are deemed less secure.
I would opt for functionality over security in such cases, understanding the potential risks and making a conscious choice to enable certain features while using third-party plugins.

**Comment by LeTaon** [comment]
Agreed, similar feature limitations have gotten away from my original purpose of using obsidian to be all in one.

**Comment by 0915xiaoxiang** [comment]
I agree, too.

**Comment by xmny** [comment]
Obsidian is **JUST OBSIDIAN** , not notion

**Comment by joethei** [comment]
Most uses of `app://local` have an alternative solution now. As a replacement, we provide the [getResourcePath](https://docs.obsidian.md/Reference/TypeScript+API/Vault/getResourcePath) methods, and the [resourcePathPrefix](https://github.com/obsidianmd/obsidian-api/blob/bbb696aeb8bf5126bf2ecbf84fc8284fe133bc20/obsidian.d.ts#L2900) variable for plugins to use.

There is a [Discord support thread](https://discord.com/channels/686053708261228577/702717892533157999/1103015210949808138) where developers can get help from the Obsidian team, and ask questions about how to migrate plugins. Additionally, we scanned for plugins that use `app://local` in their code, and notified users and developers prior to the change to make the transition as seamless as possible.

Since this isn't feedback about the API itself, please use the [Obsidian Forum](https://forum.obsidian.md/) if you would like to continue the discussion about this topic.
