### ISSUE TITLE
Bug: type definition for ColorComponent is missing property with HtmlElement

### ISSUE THREAD

**Issue by srg-kostyrko** [obsidianmd/obsidian-api#158]
I see in console output that ColorComponent has link to corresponding html element (similar to other components) called `colorPickerEl` but type definition does not have this property defined.

**Comment by lishid** [comment]
This is intentional. The API does not expose private or internal parts that are not intended for public use, because it may be changed around, renamed, etc in the future without notice. Of course the private fields are available at runtime so you can ignore the typing and use it directly at your own risk.
