### ISSUE TITLE
Bug: this.app.internalPlugins does not exist on type 'App'

### ISSUE THREAD

**Issue by dromse** [obsidianmd/obsidian-api#163]
**Steps to reproduce:**
- I wrote simple code inside `function onload()` inside my plugin
```typescript
this.app.internalPlugins.getEnabledPluginById('daily-notes')
```
![image](https://github.com/obsidianmd/obsidian-api/assets/57846319/8dc263c1-212e-4ce0-b7b1-1c936b12b3c1)
- Function works fine inside obsidian but I need to put `// @ts-ignore`

**Comment by joethei** [comment]
Private APIs are not documented because they are private.
There are loads of methods and fields that exists at runtime but aren't in the API because we have not committed to supporting them through the API.

If you decide to use a private API you can do so by adding it in your own local .d.ts file in your plugin repo.
