### ISSUE TITLE
any way to change mtime only?

### ISSUE THREAD

**Issue by fyears** [obsidianmd/obsidian-api#31]
Hi,

Is there any way to change mtime only? (which is similar to Linux's `touch` command).

I found there are `modify()` and `modifyBinary()`. But the content (`data`) must be provided, which means that though I could change the mtime by writing same content, it's very inefficient. I also tried to pass `undefined` to `data` but received no luck.

Another related issue is that the api also lacks the support of `appending file` instead of `rewriting file`. Is it also possible to do that?

Thank you so much!

**Comment by lishid** [comment]
Yeah so if I understand it correctly it will end up with something like this:

- 2020-01-01 Disconnect sync
- 2020-06-01 Modify my file "note.md"
- 2020-12-01 Reconnect sync
- Uploads note.md
- Remote now says note.md modified on 2020-12-01 (because it was just uploaded)
- Update the local mtime to 2020-12-01 (because the times don't match)
- Original mtime is now lost

Is that correct?

**Comment by lishid** [comment]
This should now be achiveable with append - just append nothing, and set the write options to overwrite the mtime.
