### ISSUE TITLE
Surefire 'quit' event or 'aboutToQuit' state

### ISSUE THREAD

**Issue by T3sT3ro** [obsidianmd/obsidian-api#57]
Can we get some surefire cleanup stage when user is about to exit the app?

I am thinking about some buffer state `aboutToQuit` hidden behind a quit confirmation dialog, when user is about to exit the app. So for example when he clicks 'X' then there would be a 'quitting' state, and if there are no callbacks registered in there, then everything exits. Otherwise a popup could display with with text describing what is being done right now and two buttons `[Cancel] [Quit anyway]`.

This way things like cleaning things up or syncing could be done easily, because user would:
1. Click `[X]` to close
2. If plugins registered for `aboutToQuit` -- display a popup prompt with update messages and buttons to cancel quitting or confirm (and force) it:
   ```
   - [Plugin1] ✔️ Cleaning empty notes...
   - [Plugin2] ⧗ Syncing files...
    
                     [Cancel][Quit anyway]
   ```
3. If all tasks finish, app quits. Otherwise Quit anyway works like now, and plugins receive best effort `quit`

**Comment by lishid** [comment]
There is already such an API [here](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L3820), but I agree there could be a better UI for when the user wants to quit.

Right now, when the user hits the x on the window, and plugins have registered callbacks with the API, we will wait up to 4 seconds for the callback promises to finish running. If the user hits the x again, or 4 seconds has passed, or if all callback promises resolves, the vault will exit.

**Comment by lishid** [comment]
Unfortunately there is no "sure fire" way to run code when the program is about to exit because there are many exit conditions that don't give us a chance - for example on mobile there's basically no chance of cleaning up. On desktop if the user choose to quit the app then it exits immediately.

The current API provides an opportunistic way to run code for up to 4 seconds before the app is killed. You can show some kind of dialog in your plugin when using the current API.
