### ISSUE TITLE
Obsidian.d.ts misses `metadataCache.getBacklinksForFile()` definition

### ISSUE THREAD

**Issue by mnaoumov** [obsidianmd/obsidian-api#58]
Based on my rough reverse-engineering it should be something like

```typescript
export class MetadataCache extends Events {
...
    getBacklinksForFile(file: TAbstractFile): { data: {[notePath: string]: LinkCache[]} };
}
```

**Comment by lishid** [comment]
Thank you, but these APIs are not included in the .d.ts files on purpose. You are free to use them by defining a copy of the definition in your codebase but beware that they are private API and may be changed at any time in a backward incompatible way.

**Comment by mnaoumov** [comment]
@lishid thanks for your quick reply. Can I ask you for the reason why the developers team decided not to expose this API to public?

From the plugin point of view, I see this API as essential. Because alternative approaches as far as I see, either traverse the entire vault manually how is it done here
https://github.com/dy-sh/obsidian-consistent-attachments-and-links/blob/master/src/links-handler.ts#L634
Which is essentially inefficient for big vaults.

Alternatively, we could build our own backlinks cache but I'd prefer to avoid doing it unless it is really justified

**Comment by lishid** [comment]
> Can I ask you for the reason why the developers team decided not to expose this API to public?

A lot of these internal functions aren't exposed because the shape of their APIs aren't yet fully decided. The specific function in question just uses the other data from `MetadataCache` by iterating through each file and using information returned from getFileCache(). You can reproduce the same code from the existing public API actually. (I think you could even go one step further and use the `resolvedLinks` object for further optimizations)

The reason for not exposing them is because they were initially created for some internal use case (this function, for example, is used for checking linked files when deleting files). For API endpoints, we usually need to think about things like naming, parameter and return type definition, and whether it makes sense as a whole along with the rest of the API.
