### ISSUE TITLE
Expose Locale information

### ISSUE THREAD

**Issue by mamoit** [obsidianmd/obsidian-api#6]
This has arisen from an [issue](https://github.com/liamcain/obsidian-calendar-plugin/issues/36) in @liamcain's calendar plugin, and the need to know if 2020 has 53 or 52 weeks, and the answer was... Depends what your locale is.

The correct way of solving this issue would be to ask the OS for its locale, but according to @liamcain, Obsidian's API does not expose it. Does it make sense to expose it to the plugins?

**Comment by lishid** [comment]
You are free to use electron's locale (`app.getLocale`) or whatever is available at the browser level (something like `navigator.language`). We don't actually have an API ourselves for that

**Comment by liamcain** [comment]
Sorry, I should clarify. The issue I was mentioning is that the `moment` module packaged with the app doesn't include the locale files. I could pull in the moment locale files myself from a plugin but I'm not sure that makes the most sense. Happy to discuss outside of the Github issue though (forum or discord probably makes more sense).

Since this isn't API related, the issue should probably be closed.

**Comment by lishid** [comment]
I think probably because moment-with-locales was a lot bigger (like 6x the size of moment.js itself) so we didn't include it.

**Comment by lishid** [comment]
I think we can add those in either way one of the next releases. In the meantime you can still customize anything you want through moment's api I think.

**Comment by mamoit** [comment]
`moment-with-locales.js` replaced `moment.js` in `v0.1.18` insider build, which fixes the issue.
Sorry filing the issue when I didn't know what the root issue was.
Thank you both for working it out despite my mess :tada:

**Comment by isaaclyman** [comment]
@lishid It's not clear to me how to use `app.getLocale` from plugin code. Obsidian's API exposes an `app` global but it doesn't have a `getLocale` method and doesn't seem to be the same `app` exposed by Electron. How can I access that?

**Comment by lishid** [comment]
you need the electron `app` object which you can get from `electron.remote.app`.

**Comment by isaaclyman** [comment]
Thanks, but where does `electron` come from? VS Code doesn't recognize it as a global or something that can be imported.

**Comment by lishid** [comment]
you can either get it from `window.require('electron')` or `window.electron` - it's not defined in the type files but you can create an override declaration yourself in your project. The reason it's not defined out of the box is because it doesn't exist on mobile and thus isn't an API that's always available (so you should check if it's defined before attempting to use it).

**Comment by isaaclyman** [comment]
I see, thank you. It sounds like that's pretty limited, then, if it only works on desktop.

I've been hearing from users of my plugin outside the US that number and date formatting aren't following their computer's locale. I can add a locale override to the plugin settings, but I was really hoping to be able to auto-detect it somehow.
