### ISSUE TITLE
Wrapping CodeMirror.Editor with Obsidian.Editor?

### ISSUE THREAD

**Issue by PeteMichaud** [obsidianmd/obsidian-api#61]
As I mentioned in another issue, I'm trying to update the Text Snippets plugin, and one thing I'm doing is moving all `CodeMirror.Edtior` references over to the Obsidian abstraction.

One problem I have is that various callbacks including the one for `Plugin().registerCodeMirror()` function passes an instance of `CodeMirror.Editor` but there's no way to wrap that instance in an `Obsidian.Editor`. 

Right now I am getting the Obsidian editor whenever I need it this way:

```
getEditor(): Editor {
	const markdownView = this.app.workspace.activeLeaf.view as MarkdownView;
	return markdownView.editor
}
```

Which feels circuitous and wrong, but I'm not sure about a better way because I can't use the editor instance I get from either `registerCodeMirror` or from `cmEditor.on('key...', (ed, ev)=>...)`

Not sure if we need a wrapper here, or if the API should be updated to just pass an Obsidian.Editor?

**Comment by lishid** [comment]
`registerCodeMirror` only works with the legacy editor - it is a no-op for most people who are using the new cm6-based editor.
`cmEditor.on` is also not directly available to be translated to the new editor. Depending on how much custom code you need to run, you may have to write code specifically for the new editor.

You should also use `workspace.getActiveViewOfType(MarkdownView)` and perform a null check with the result instead of directly addressing `activeLeaf` and cast it to a MarkdownView (because it's not always a MarkdownView).

**Comment by lishid** [comment]
Also the issues here are intended for actual faults within the API. For questions and how-to's please use the discord server and discuss your questions with other plugin devs. There's a channel for `#plugin-dev`.

**Comment by PeteMichaud** [comment]
Sorry, I appreciate the help, I thought this might an unintentional gap in the API.
