### ISSUE TITLE
Update @codemirror/view to 0.20

### ISSUE THREAD

**Issue by zoli** [obsidianmd/obsidian-api#64]
As of [@codemirror/view v0.20.0](https://github.com/codemirror/view/releases/tag/0.20.0) per line direction is enabled. So if obsidian updates to > 0.20.0 (its currently 0.19.31). Through the plugins we will be able to have better support for RTL languages.

related discussions https://github.com/codemirror/codemirror.next/issues/782 and https://github.com/esm7/obsidian-rtl/issues/18

**Comment by lishid** [comment]
Yeah that's going to happen eventually but not for a while.

0.20 has removed and moved a ton of APIs around and we'll need to coordinate a release with existing cm6 plugins to avoid breaking them all in one go.

**Comment by aidenlx** [comment]
one small suggestion, since codemirror packages is required to include in their dependencies for plugins so that the types can work correctly, including them in [`peerDependencies`](https://nodejs.org/es/blog/npm/peer-dependencies/) might be a good idea because: 

1. it will show a warning during `npm install` whenever the installed version doesn't fit peerDependencies's requirement
2. it can avoid [Phantom dependencies](https://rushjs.io/pages/advanced/phantom_deps/) issues when using pnpm

**Comment by lishid** [comment]
Good idea!
