### ISSUE TITLE
'obsidian' not defined?

### ISSUE THREAD

**Issue by leonhma** [obsidianmd/obsidian-api#66]
Hello. Im currently writing a plugin that i need to work for android. I had a working version using rollup, but that didn't package certain node related stuff, so i switched to webpack. Everything gets bundled nicely, as far as i can tell (im somewhat of a newbie to typescript and bundlers), but when i enable the plugin, devtools tells me that 'obsidian is not defined'. (repo here: https://github.com/leonhma/obsidian-functionplot). What i have done is registered loaders for typescript, and marked 'obsidian' as an external global variable (one that is provided at runtime). Do you know whats going wrong? Cause i dont...

**Comment by lishid** [comment]
I don't know either - our newest sample plugin uses `esbuild` instead which works much faster than rollup and webpack. Seems like your repo isn't generated from the template so I don't know. You also don't have the compiled release uploaded to github releases so I can't easily check your compiled file for how it turned out.

Lastly, please head to the discord server under the `#plugin-dev` channel for help with using the API. Issues in this repo is meant for actual bugs with the API, not questions. It's also not watched by other plugin developers, and as such you won't receive as much help.
