### ISSUE TITLE
Bug: Metadatacache.on('changed', ...) is not called on file renames

### ISSUE THREAD

**Issue by PawanHegde** [obsidianmd/obsidian-api#77]
**Steps to reproduce:**
- Run the following command in the developer console of Obsidian.
```
this.app.metadataCache.on("changed", (file, data, cache) => console.log(file.name + " changed")));
```
- If you change some content in a markdown file, the event is fired and you'll see a log in the console, but if you rename the same markdown file, the event is not fired even though the metadata about the file changed.

**Comment by lishid** [comment]
Thanks, will look into this.

**Comment by lishid** [comment]
Ok just reviewed and this is on purpose. If you need to know both then you will need to hook up both events.

The reasoning is two ways:
- The changed event send out the file data at the time of parsing/indexing, but on rename, files aren't read, which means it will be more performance intensive to read all the files on rename (you can trigger a massive rename event by renaming a high level folder).
- Plugins (and internal code) typically treat renames slightly different (for example, by remapping data instead of recomputing data), so triggering change events for renames would mean that plugins cannot discern whether a change was the result of an actual file change, or an unchanged file being renamed, which will lead to more re-computations than necessary.

Therefore closing as wontfix.

I will look into adding some documentation to make this clear. Thanks for raising the concern though.

**Comment by PawanHegde** [comment]
Thanks, Lishid.
